// <auto-generated />
using System;
using AttendanceMonitoringSystem.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AttendanceMonitoringSystem.Migrations
{
    [DbContext(typeof(StudentAttendanceDbContext))]
    [Migration("20250916090429_AttendanceMonitoringSystem")]
    partial class AttendanceMonitoringSystem
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("AttendanceMonitoringSystem.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool?>("Status")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("TimeIn")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("TimeOut")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("Attendance");
                });
#pragma warning restore 612, 618
        }
    }
}
